*** Starting uWSGI 2.0.21 (64bit) on [Sat Jun 10 14:37:11 2023] ***
compiled with version: 11.3.0 on 10 June 2023 10:20:58
os: Linux-5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021
nodename: Anonymous
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /mnt/c/Users/USER/Desktop/Projects/Talkify
detected binary path: /home/fortune/.local/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 15500
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5000 fd 3
Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Python main interpreter initialized at 0x5639550109e0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 700088 bytes (683 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 6 seconds on interpreter 0x5639550109e0 pid: 33 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 33, cores: 4)
spawned uWSGI worker 2 (pid: 34, cores: 4)
Invalid session CFRjDniUhRutLxxVAAAA (further occurrences of this error will be logged with level INFO)
Invalid session CFRjDniUhRutLxxVAAAA (further occurrences of this error will be logged with level INFO)
Invalid session fKGosA37BMXyBP1CAAAA (further occurrences of this error will be logged with level INFO)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2213, in __call__
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
    return self.wsgi_app(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 43, in __call__
  File "/home/fortune/.local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/middleware.py", line 63, in __call__
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/socketio/server.py", line 607, in handle_request
  File "/home/fortune/.local/lib/python3.10/site-packages/socketio/server.py", line 607, in handle_request
    return self.eio.handle_request(environ, start_response)
    return self.eio.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/server.py", line 410, in handle_request
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/server.py", line 410, in handle_request
    packets = socket.handle_get_request(
    packets = socket.handle_get_request(
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 103, in handle_get_request
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 103, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
    return getattr(self, '_upgrade_' + transport)(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 158, in _upgrade_websocket
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 158, in _upgrade_websocket
    return ws(environ, start_response)
    return ws(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/async_drivers/threading.py", line 22, in __call__
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/async_drivers/threading.py", line 22, in __call__
    self.ws = Server(environ)
    self.ws = Server(environ)
  File "/home/fortune/.local/lib/python3.10/site-packages/simple_websocket/ws.py", line 319, in __init__
  File "/home/fortune/.local/lib/python3.10/site-packages/simple_websocket/ws.py", line 319, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
RuntimeError: Cannot obtain socket from WSGI environment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/socketio/server.py", line 607, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/server.py", line 410, in handle_request
    packets = socket.handle_get_request(
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 103, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 158, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/async_drivers/threading.py", line 22, in __call__
    self.ws = Server(environ)
  File "/home/fortune/.local/lib/python3.10/site-packages/simple_websocket/ws.py", line 319, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/socketio/server.py", line 607, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/server.py", line 410, in handle_request
    packets = socket.handle_get_request(
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 103, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 158, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/async_drivers/threading.py", line 22, in __call__
    self.ws = Server(environ)
  File "/home/fortune/.local/lib/python3.10/site-packages/simple_websocket/ws.py", line 319, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/socketio/server.py", line 607, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/server.py", line 410, in handle_request
    packets = socket.handle_get_request(
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 103, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 158, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/async_drivers/threading.py", line 22, in __call__
    self.ws = Server(environ)
  File "/home/fortune/.local/lib/python3.10/site-packages/simple_websocket/ws.py", line 319, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
good
its working
pls
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/socketio/server.py", line 607, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/server.py", line 410, in handle_request
    packets = socket.handle_get_request(
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 103, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 158, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/async_drivers/threading.py", line 22, in __call__
    self.ws = Server(environ)
  File "/home/fortune/.local/lib/python3.10/site-packages/simple_websocket/ws.py", line 319, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/socketio/server.py", line 607, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/server.py", line 410, in handle_request
    packets = socket.handle_get_request(
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 103, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 158, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/async_drivers/threading.py", line 22, in __call__
    self.ws = Server(environ)
  File "/home/fortune/.local/lib/python3.10/site-packages/simple_websocket/ws.py", line 319, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
again
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/socketio/server.py", line 607, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/server.py", line 410, in handle_request
    packets = socket.handle_get_request(
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 103, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/socket.py", line 158, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/fortune/.local/lib/python3.10/site-packages/engineio/async_drivers/threading.py", line 22, in __call__
    self.ws = Server(environ)
  File "/home/fortune/.local/lib/python3.10/site-packages/simple_websocket/ws.py", line 319, in __init__
    raise RuntimeError('Cannot obtain socket from WSGI environment.')
RuntimeError: Cannot obtain socket from WSGI environment.
sharp
